### ISSUE TITLE
Не работает =(

### ISSUE THREAD

**Issue by khseal** [sprilukin/lib_BL999#1]
Какую версию среды для ардуино вы используете и какой приемник?
Что-то у меня совсем не работает ваша библиотека. Используют приемник с супергетеродином.
Хотя возможно у меня руки кривые...
Неплохо бы режим отладки какой-то сделать.

**Comment by sprilukin** [comment]
У меня последняя версия среды 1.6.x не помню последюю цифру. Тестировал вот на таком приемнике http://arduino-ua.com/prod247-Radioydlinitel_433Mgc
Тестировал также на arduino uno, arduino pro mini, esp8266 - везде работает. Насчет режима отладки - Вы правы, нужно бы добавить. Напишите, пожалуйста конкретнее что именно не работает - не компилится или не получает данные?

**Comment by khseal** [comment]
Нет данных. У меня есть, такой же как у вас приемник попробую его. Но этот приемник очень чувствителен к качеству питания. У меня он очень не устойчиво работал когда брал для него питание с роутера. Приемники с супергетеродином работают намного устойчивей.
Вот начал писать к ардуинам по мелочи, везде какие-то глюки. Теперь я понимаю почему серьезные проекты на ардуинах редко делают. 
Возможно виновата Windows 10 надо попробовать на вин 7 с ней поработать.
Мне везет на хитрые баги...

**Comment by sprilukin** [comment]
Приемник действительно слабоват, через толстую стену уже не ловит даже на расстоянии в 3 метра. Поэтому при отладке передатчик держал в пределах прямой видимости. Ардуино так и позиционируется для хобби проектов, хотя сам чип  atmega который там используется полне можно использовать и для серьезных проектов. Как правило, его возможностей выше крыши. Сейчас использую вместо ардуино микроконтроллер с Wi-Fi - esp8266. По сравнению с ардуино это просто зверь ), особенно для всякого интернета вещей. Писать так же просто как и для ардуино.

**Comment by khseal** [comment]
esp8266 весьма неплох, но потребляет тоже хорошо. Работать от аккумулятора продолжительное время к сожалению она не будет =(
А у меня ардуина глючит весьма странно, то ли в среде проблема то ли в китайских ардуинах.
Компилируешь прошивку заливаешь в ардуину проверяешь все работает. Переподключаешь питание ардуины и ардуина начинает тормозить и практически не работать. Делаешь ресет ардуины все нормально. 
Проблема воспроизводится на любых простейших программах...
Вопрос еще по указанию пина. У вас в библиотеке он уже указан, как я понимаю в примере пин переопределяется командой
bl999_set_rx_pin(6);
Плюс у вас указано что это дигитал пин. Т.е. если использовать ардуино про микро. То указывать надо тот пин который подписан на плате. А то я путаю постоянно аналоговые пины и цифровые.
Попробовал другой приемник все равно не работает...

Мы для этого датчика делали обработку под Openwrt c помощью гпио. Но там все получилось через задницу т.к. в той модели роутера на гпио нельзя реализовать прерывание, плюс я так и не сообразил как сделать подсчет crc..
При отладке делали вывод сигнала в виде 0 и 1...

**Comment by sprilukin** [comment]
Да, все верно - нужно использовать цифровой пин, но есть особенность, что нужно использовать такой цифровой пин на который можно повесить прерывание. У ардуино не на все пины можно повесить прерывания: https://www.arduino.cc/en/Reference/AttachInterrupt
Напримар на Uno это только два цифровых пина -  №2 и №3

Насчет плохой работы ардуины -  у меня такая проблема бывает с esp8266, в моем случае это скорее проблема с USB портом - похоже он перестает выдавать необходимую силу тока, работает только после перезагрузки компа...

**Comment by khseal** [comment]
Спасибо за наводку про пины, наверное дело в этом. Надо было в описании добавить про эту особенность)
Питание USB тут не причем. Т.к. пробовал запитывать от отдельного блока питания. Мне кажется все же дело либо в загрузчике либо в среде. Хотя этот глюк я встречал где-то раньше...

**Comment by sprilukin** [comment]
Да, моя вина - не добавил в описание. Уже исправил

**Comment by sprilukin** [comment]
насчет esp8266 - если включить deep sleep и слать данные не часто, например раз в 5 минут, то вполне может работать от батареи - потребление в режиме передачи ~170mA в режиме deep sleep ~10uA, можно вообще добавить внешний микроконтроллер с ультранизким потреблением , который будет выключать\включать esp8266 через ногу CH_PD. В режиме POWER off, когда CH_PD не подключена к VCC потребление 0,5uA  http://bbs.espressif.com/viewtopic.php?t=133

**Comment by khseal** [comment]
Можно, но это уже издержки. Прикрутил приемник к ноге с прерываниями. Данные появились.
Но какие-то странные и только от одного датчика...
====== Got message: 
2
59
0
48
59

**Comment by sprilukin** [comment]
ну все верно, поздравляю все заработало.
2 - канал датчика,
59 - это UUID можно сказать мусорные данные, так как после выключения\включения датчика эта цифра сменится
0  - батарея в порядке
48 - температура \* 10,  т.е. 4.8 градуса
59 - влажность 59%

**Comment by khseal** [comment]
Ок, а он по всем каналам ищет? У меня датчик на первом канале есть который рядом. А второй датчик на втором канале в холодильнике стоит)) 
С данными разобрался вроде бы соответствуют действительности.

**Comment by sprilukin** [comment]
да, ищет по всем каналам. Подождите немного - у меня иногда может час не читать от определенного датчика, не знаю почему, скорее всего из-за дешевого приемника.
Если датчик стоит рядом - поставьте подальше, на расстояние не меньше длинны волны - ~68 см

**Comment by sprilukin** [comment]
так как данные получены, с Вашего позволения отмечаю issue  как closed

**Comment by khseal** [comment]
Ну не совсем рядом, но в прямой видимости. Я использую другой приемник с ним не должно быть проблем.  Я использую вот такой датчик http://www.ebay.com/itm/Super-heterodyne-OOK-Wireless-Receiver-Module-Strong-Interference-433MHZ-Good-/171504956208?hash=item27ee7df330

Спасибо за разработку и помощь.

**Comment by sprilukin** [comment]
Всегда пожалуйста! Рад, что библиотека пригодилась не только мне )

**Comment by sprilukin** [comment]
Немного изменил тайминги для бита-разделителя - возможно из за этого не видело датчик на другом канале - проверьте на последней версии.

**Comment by khseal** [comment]
Датчики сейчас все видит, но иногда бывают какие-то у него затупы по одному из датчиков. Грешу на приемники. Т.к. у одного приемника затупы с одним датчиком, а другого приемника со вторым датчиком.
Хотя в последнее время все стабильно работает.
