### ISSUE TITLE
Проблемы с компилированием исходников в MariaMole

### ISSUE THREAD

**Issue by khseal** [sprilukin/lib_BL999#2]
Решил тут воспользоваться альтернативами средами под Arduino. А то родной Arduino IDE что-то не очень мне нравится. 
Натолкнулся вот на такую ошибку
lib_bl999.cpp (34):  'digitalPinToInterrupt' was not declared in this scope
Как я понимаю данную функцию надо декларировать в хедере?

**Comment by sprilukin** [comment]
Да, попробуйте подключить

#include <pins_arduino.h>

вот тут видно, что digitalPinToInterrupt находится в этом заголовочном файле.
https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/variants/standard/pins_arduino.h

**Comment by sprilukin** [comment]
Я использую [PlatformIO](http://platformio.org/#!/) + [CLion](https://www.jetbrains.com/clion/)
вот [тут](http://docs.platformio.org/en/latest/ide/clion.html) инструкция как их подружить.

Очень доволен, рекомендую.

**Comment by khseal** [comment]
`#include <pins_arduino.h>` не помогло. 
Да видел вашу инструкцию, но я балуюсь ардуиной на Windows и как это все собрать под винду пока не понятно.

**Comment by sprilukin** [comment]
попробую эту MariaMole запустить на маке  если получиться (нужно самому из сорсов собирать)

Моя инструкция под IDEA, а там не так удобно как в CLion c ардуино работать. CLion как раз заточен под C/C++
там и автодополнение кода будет и компиляция\прошивка удобнее. У меня продуктивность на порядок выросла когда перешел на эту связку.

Под винду там все просто - нужно только интерпретатор [питона установить](https://www.python.org/downloads/release/python-2711/) и не забыть галочку поставить чтобы в  PATH прописалось, чтобы можно было из консольки команды выполнять. Дальше для всех платформ одинаково:
- открываем терминал
- `pip install -U platformio` (если не работает то сначала выполняем `easy_install pip`)
- далее генерим проект под нашу платформу:
- создаем папочку для проекта
- в этой папочке в терминале выполняем `platformio init --ide clion --board=uno`    (это если под уно писать будем. список всех платформ [тут](http://platformio.org/#!/boards?filter%5Bplatform%5D=atmelavr))
- после этого каркас проекта готов. в папочке src создаем наш скетч и редактируем любым редактором.
- Заливка на МК:
- `platformio run --target upload`  usb порт само определит

Интеграция с CLion (если с ним не получится\не понравиться то можно [Platformio IDE](http://platformio.org/#!/get-started) использовать, но я ее не пробовал):
- Качаем и ставим CLion
- далее по [этому пошаговому](http://docs.platformio.org/en/latest/ide/clion.html) гайду

проблем возникнуть не должно

единственное что если сначала сгенерили прооект, а только потом добавили в src скетч файл то нужно его ручками добавить в CMakeLists.txt что в корне проекта:

```
#
# To enable code auto-completion, please specify path
# to main source file (*.c, *.cpp) and uncomment line below
#
add_executable(esp8266_mqtt src/your_sketch_name.cpp)
```

ах да, если будете использовать [мою либу](http://platformio.org/#!/lib/show/564/lib_bl999) то ее сначала нужно установить тоже из консольки:

`platformio lib install 564`

после этого в скетче можно писать 
`#include <lib_bl999.h>`

**Comment by khseal** [comment]
Не совсем простая инструкция =) Просто я больше по железу разбираюсь, с программированием не очень люблю возиться. Хотя если будет время, попробую собрать велосипед..

**Comment by sprilukin** [comment]
Ну просто эта MariaMole  похожа на поделку на коленке, инфы как собрать под мак нет, так что не могу проверить к сожалению...
попробуйте Platformio IDE
на офф сайте инструкция более подробная должна быть

**Comment by khseal** [comment]
Да, думаю это проблема самой MariaMole. Хотя Arduino IDE от коленки не далеко ушла(

**Comment by sprilukin** [comment]
Да, просто создатели Arduino IDE больше внимания уделили общей инфраструктуре ардуино проекта - toolchain, подробный конфиг вариантов МК и т.д. . Эту инфраструктуру теперь как раз и использует platformIO. Создать хорошую IDE это не тривиальная задача, поэтому и предлагаю использовать platformio в качестве низкоуровневого менеджера ардуино проекта в связке с одним из лидеров С++ IDE. Это может быть Visual Studio, CLion, eclipse либо другие - там есть и автодополнение кода, и подсветка синтаксиса и много других плюшек.
вот [тут](http://docs.platformio.org/en/latest/ide.html) описание связки для всех популярных IDE
Я использую IntelliJ CLion потому что в основном использую IntelliJ IDEA и мне просто так удобнее.
