### ISSUE TITLE
Влажность 99

### ISSUE THREAD

**Issue by ZiP0iP** [sprilukin/lib_BL999#4]
Добрый вечер. В чем может быть проблема. Все время влажность 99%, температуру показывает

**Comment by sprilukin** [comment]
Есть два типа датчиков - с температурой и влажностью и только с температурой.
Если датчик поддерживает влажность то на передней панели должно быть написано Temp and humidity.

**Comment by ZiP0iP** [comment]
Да, без датчика влажности. Спасибо.

**Comment by furyalex** [comment]
Добрый день,

Есть ли возможность допаять сенсор влажности? На плате, вроде, есть место для сенсора. Есть ли где-нибудь схема сенсора?
