### ISSUE TITLE
Резисторы на плате

### ISSUE THREAD

**Issue by furyalex** [sprilukin/lib_BL999#6]
Добрый день,

Добыл BL999 модуль для метеостанции. К сожалению, в моем модуле отсутствует датчик влажности. Плата таже -- 9021AT1. Похоже, что нехватает только R6, R8, и RH (датчик влажности). Подскажите, пожалуйста, какие у этих резисторов номиналы?

Понимаю, что не совсем по теме репозитория, но не смог ни где найти схему этого чуда. Заранее спасибо!

**Comment by khseal** [comment]
А эти датчики посылают данные о влажности? Я думаю, что если программно влажность вырезана, то резисторы не помогут. Т.е. если изначально параметров влажности нет, они магическим образом вряд ли появятся при запайке резисторов...

**Comment by furyalex** [comment]
Датчик шлет 99%, что похоже на граничное значение. Плата там та же, что и у датчика, который шлет влажность, номер на плате тот же. Поэтому, я подожреваю, что там та же программа на контроллере и если допаять резисторы, то заработает. Еще вместо кондетсатора C12 впаяна перемычка.

**Comment by khseal** [comment]
Ну если шлет то да поможет, но мне крайне лениво снимать датчик и смотреть что там как. Я не помню у этих датчиков меняется id при отключении батареек?

**Comment by furyalex** [comment]
Может схемы где есть?

**Comment by khseal** [comment]
Схем точно на такое нет, если ID не сбрасывается я могу глянуть наверное резисторы. Хотя може я глючу насчет ID надо свои проекты глянуть.

**Comment by furyalex** [comment]
спасибо!

**Comment by sprilukin** [comment]
@furyalex
ID сбрасывается если батарейки вытащить

![Фото платы](https://user-images.githubusercontent.com/1129834/71355942-567cfb00-2589-11ea-8774-092bff4e84c9.jpg)

**Comment by furyalex** [comment]
Спасибо!

Sincerely,
Alexander Aksenov
mob. +1 (206) 331-0764

**Comment by ivan-ef** [comment]
Как бы ещё узнать номинальное сопротивление датчика влажности или его маркировку чтобы похожий подобрать.
