### ISSUE TITLE
ESP8266 отказывается дружить с данной библиотекой

### ISSUE THREAD

**Issue by metal446344002** [sprilukin/lib_BL999#7]
Добрый день!
Имею парочку esp8266 и вот как то захотелось сделать из них сборщиков данный с bl999
Но в сожалению, все то получается - это циклический перезапуск
Кто заводил данну
![Screenshot_1](https://user-images.githubusercontent.com/66744180/99294026-e9d3b480-285c-11eb-8d58-b30f23596948.png)
ю библиотеку - как победить это?
Я понимаю, что делаю что-то явно не так, но не пойму где загвоздка

**Comment by khseal** [comment]
На форумах вроде описана эта проблема. Затык в работе с прерываниями.
Пишут что это решает проблему.
Ключевым в вашем выводе с ESP8266 было "ISR not in IRAM!"

Надо объявить вашу функцию до setup() в виде:

void ICACHE_RAM_ATTR function();

Тогда скетч будет нормально работать с функцией function() назначенной прерыванию.

Таким образом надо объявлять дополнительно все функции вызываемые по прерываниям

**Comment by metal446344002** [comment]
Ложная тревога - неделя мучений вроде закончена. Плата - rbnfqcrfz NodeMCU v1. Проблема решилась  просто - откат менеджера плат на версию 2,4,2 - и не требуются ни какие  дополнительные параметры для вызова процедур. Про ICACHE_RAM_ATTR я читал и пробовал - на новом менеджере плат эффекта мне не дало. Может кому пригодится , ибо я думаю не один с такой бедой столкнулся
